In [179]:
from sklearn.datasets import load_iris
import numpy as np

In [180]:
data = load_iris()

In [181]:
X = data.data
y = data.target

In [182]:
print(X.shape)

(150, 4)


In [183]:
print(y.shape)

(150,)


In [184]:
print(list(data.target_names))

['setosa', 'versicolor', 'virginica']


In [185]:
y[y == 0] = 0
y[y == 1] = 0
y[y == 2] = 1

In [186]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [187]:
print(y.shape)

(150,)


In [188]:
def sigmoid(X):
    return 1 / (1 + np.exp(-X))

In [189]:
theta = np.ones(X.shape)

In [190]:
print(theta)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1.

In [191]:
print(theta.shape)

(150, 4)


In [192]:
num_iterations = 1500
learning_rate = 0.01

In [193]:
for i in range(num_iterations):
    # Bereken de voorspellingen
    z = np.dot(X, theta.T)
    predictions = sigmoid(z)
    
    # Bereken de fouten (kosten)
    errors = predictions - y
    
    # Bereken de gradient en pas theta aan
    gradient = np.dot(errors, X) / len(y)
    theta -= learning_rate * gradient
    
    # Bereken de kosten voor deze iteratie
    cost = (-1 / len(y)) * np.sum(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    
    # Print de kosten voor elke 100 iteraties
    if i % 100 == 0:
        print(f"Iteratie {i}: Kosten = {cost}")

Iteratie 0: Kosten = 1385.8027324953912
Iteratie 100: Kosten = 576.2021322075825
Iteratie 200: Kosten = 1244.6762856282628
Iteratie 300: Kosten = inf


C:\Users\marti\AppData\Local\Temp\ipykernel_24888\1404298078.py:14: RuntimeWarning: divide by zero encountered in log
  cost = (-1 / len(y)) * np.sum(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))


Iteratie 400: Kosten = inf
Iteratie 500: Kosten = inf
Iteratie 600: Kosten = inf
Iteratie 700: Kosten = inf
Iteratie 800: Kosten = inf
Iteratie 900: Kosten = inf
Iteratie 1000: Kosten = inf
Iteratie 1100: Kosten = inf
Iteratie 1200: Kosten = inf
Iteratie 1300: Kosten = inf
Iteratie 1400: Kosten = inf
